# ClickHouse Backend configuration
# ################################
# backend: clickhouse
db_host: localhost
db_port: 8443
db_name: xapi_lt
db_event_sink_name: event_sink
db_username: ch_admin
db_password:
s3_key:
s3_secret:


# Ralph / ClickHouse backend configuration
# ########################################
#backend: ralph_clickhouse
#db_host: localhost
#db_port: null
#db_name: xapi
#db_username: ch_admin
#db_password: 7NRe69D4zWWT0rf2G7gWa7RB
#lrs_url: http://ralph.tutor-nightly-local.orb.local/xAPI/statements
#lrs_username: ralph
#lrs_password: sdtiqjqwixhzcboqzbiryrulzcpvfmsfvqqw

# CSV backend configuration
# #########################
backend: csv_file
# This can be anything smart_open can handle, a local directory or
# an S3 bucket, etc., but importing to ClickHouse only supports S3 right now
# https://pypi.org/project/smart-open/
csv_output_destination: s3://openedx-aspects-loadtest/logs/large_test/
csv_load_from_s3_after: true

# Load from S3 configuration
# ##########################
s3_source_location: https://openedx-aspects-loadtest.s3.amazonaws.com/logs/large_test/

# Run options
run_distribution_queries: false
log_dir: logs
num_batches: 10000
batch_size: 30000

# Overall start and end date for the entire run
start_date: 2014-01-01
end_date: 2023-11-27

# All courses will be this long, and be fit into the start / end dates
# This must be less than end_date - start_date days.
course_length_days: 120

# The size of the test
num_organizations: 3
num_courses: 20
num_actors: 10000

# Distribution of the size of the courses
course_size_pct:
  small: 20
  medium: 30
  large: 40
  huge: 10

# Course size configurations, how many of each type of object are created for
# each course of this size. "actors" must be less than or equal to "num_actors".
course_size_makeup:
  small:
    actors: 30
    problems: 20
    videos: 10
    chapters: 3
    sequences: 10
    verticals: 20
  medium:
    actors: 500
    problems: 40
    videos: 20
    chapters: 4
    sequences: 20
    verticals: 30
  large:
    actors: 5000
    problems: 80
    videos: 30
    chapters: 5
    sequences: 40
    verticals: 80
  huge:
    actors: 10000
    problems: 160
    videos: 40
    chapters: 10
    sequences: 50
    verticals: 100
