# Write a large amount of data to S3 using CHDB to write the ClickHouse native format
# (lz4 compressed), then load from S3 to ClickHouse

backend: chdb

db_host: localhost
db_port: 8123
db_name: xapi
db_event_sink_name: event_sink
db_username: ch_admin
db_password: ...

load_from_s3_after: true

# CHDB_S3 backend configuration
# #############################
#chdb_s3_output_destination: logs/async_test/
#chdb_s3_load_from_s3_after: true
# This number is used for each process that use workers, currently xAPI file generation,
#initial enrollment file generation, and db loading from S3. So if this value is 30, then the
# total number of workers will be 30 * 3 = 90
num_workers: 4

# Load from S3 configuration
# ##########################
s3_bucket: ...
s3_prefix: logs/async_test/
s3_key: ...
s3_secret: ...

log_dir: logs
num_xapi_batches: 5 # 600
batch_size: 10000

# All courses and events will fall between these dates
start_date: 2020-01-01
end_date: 2024-04-01

# All courses will be this long, and be fit into the start / end dates
# This must be less than end_date - start_date days.
course_length_days: 120

# The size of the test
num_organizations: 5
num_actors: 2000000

# This replicates users updating their profiles several times, creating
# more rows
num_actor_profile_changes: 2

# The sum of these is the total number of courses created for the test
num_course_sizes:
  small: 200
  medium: 400
  large: 480
  huge: 120

# How many times each course will be "published", this creates a more realistic
# distribution of course blocks where each course can be published dozens or
# hundreds of times while it is being developed.
num_course_publishes: 10

# Course size configurations, how many of each type of object are created for
# each course of this size. "actors" must be less than or equal to "num_actors".
# For a course of this size to be created it needs to exist both here and in
# "num_course_sizes".
course_size_makeup:
  small:
    actors: 100
    problems: 20
    videos: 10
    chapters: 3
    sequences: 10
    verticals: 20
    forum_posts: 20
  medium:
    actors: 1000
    problems: 40
    videos: 20
    chapters: 4
    sequences: 20
    verticals: 30
    forum_posts: 40
  large:
    actors: 2000
    problems: 80
    videos: 30
    chapters: 5
    sequences: 40
    verticals: 80
    forum_posts: 200
  huge:
    actors: 3000
    problems: 160
    videos: 40
    chapters: 10
    sequences: 50
    verticals: 100
    forum_posts: 1000
